### ISSUE TITLE
Error when patching with VHBL

### ISSUE THREAD

**Issue by CVid805** [SilicaAndPina/psvimgtools-frontend#39]
When I try to patch a game I keep getting this error. 

> Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "easyinstallers\VHBL\chooseBackupVHBL.py", line 138, in <lambda>
    self.Button1.configure(command = lambda: patch(defs.getTitleID(self.backupList.get(ACTIVE))))
  File "easyinstallers\VHBL\chooseBackupVHBL.py", line 52, in patch
    unsign_support.goUnsign(backup,CMA)
  File "unsign_support.py", line 86, in goUnsign
IOError: [Errno 13] Permission denied: 'keys/'

 Do you know what could be causing this?

**Comment by TheJordanFactor** [comment]
I am having the exact same problem. Any help would be greatly appreciated.

**Comment by CVid805** [comment]
I ended up using the 32 bit version on 0.5.2 and worked fine. Hope this helps you.

**Comment by TheJordanFactor** [comment]
Thanks!

**Comment by SilicaAndPina** [comment]
for some reason when you install PSVIMGTOOLS-FRONTEND its going to C:\PROGRAMDATA instead of %appdata% so running the application as administrator, or using the .ZIP verision should fix it . . .

**Comment by SilicaAndPina** [comment]
Just fixed some things try it now.

**Comment by joebrennannet** [comment]
Still having the same problem on both 32 and 64 bit versions

`Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "imgtools\easyinstallers\VHBL\chooseBackupVHBL.py", line 129, in <lambda>

  File "imgtools\easyinstallers\VHBL\chooseBackupVHBL.py", line 43, in patch
  File "imgtools\unsign_support.py", line 86, in goUnsign
IOError: [Errno 22] invalid mode ('r') or filename: 'keys/'`
